### ISSUE TITLE
Error message for missing git command

### ISSUE THREAD

**Issue by antage** [meh/rust-hidapi-sys#5]
When I try to build crate with 'build' feature and git command isn't installed, cargo panicked with the message 'File not found'. It doesn't explain the problem and uninformative.

It would be nice if build.rs explains missing git problem more detailed. I like how it done in [openssl-sys/build.rs](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs).

**Comment by meh** [comment]
Fixed on master.
